version: "3.0"

volumes:
  database:

services:
  frontend:
    build: ./angular8-app
    labels:
      - "traefik.backend=frontend"
      - "traefik.frontend.rule=Host:demo-app.local"
    depends_on:
      - backend
      - database
      - reverse-proxy
  
  backend:
    build: ./springboot2-app
    labels:
      - "traefik.backend=backend"
      - "traefik.frontend.rule=Host:api.demo-app.local"
    links:
      - database
    
  database:
    image: postgres:10
    labels:
      - "traefik.enable=false"
    environment:
      - POSTGRES_USER=${DEMO_APP_DB_USERNAME}
      - POSTGRES_PASSWORD=${DEMO_APP_DB_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data

  reverse-proxy:
    image: traefik:1.7.12
    labels:
      - "traefik.enable=false"
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml